// Generated by gfwlist2pac in precise mode
// https://github.com/clowwindy/gfwlist2pac

var proxy = "PROXY 61.183.128.2:5010";

var rules = [
  ".lsxszzg.com", 
  "||altrec.com", 
  "||azubu.tv", 
  "||beeg.com", 
  "||darpa.mil", 
  "||fastpic.ru", 
  "||fxnetworks.com", 
  "hulu.com", 
  "huluim.com", 
  "|http://www.ilovelongtoes.com/", 
  "||metarthunter.com", 
  "||muzu.tv", 
  "|http://www.nbc.com/live", 
  "||netflix.com", 
  "||pandora.com", 
  ".pandora.tv", 
  "|http://www.parkansky.com", 
  "|http://*.pimg.tw/", 
  "||pure18.com", 
  "||rdio.com", 
  "|http://cdn*.search.xxx/", 
  "||slacker.com", 
  "||spotify.com", 
  "||springboardplatform.com", 
  "||target.com", 
  "||turntable.fm", 
  "||vevo.com", 
  "||zattoo.com", 
  "||qq.co.za", 
  "||zozotown.com", 
  ".0rz.tw", 
  "|http://0rz.tw", 
  "||0to255.com", 
  "1-apple.com.tw", 
  "||1-apple.com.tw", 
  ".10conditionsoflove.com", 
  "||10musume.com", 
  "123rf.com", 
  ".12bet.com", 
  "||12bet.com", 
  ".12vpn.com", 
  "||12vpn.com", 
  "141hongkong.com/forum", 
  ".17t17p.com", 
  ".173ng.com", 
  "||173ng.com", 
  "1984bbs.com", 
  "||1984bbs.com", 
  ".1984bbs.org", 
  "||1984bbs.org", 
  ".1bao.org", 
  "|http://1bao.org", 
  "||1pondo.tv", 
  ".1eew.com", 
  ".2-hand.info", 
  ".2000fun.com/bbs", 
  ".2008xianzhang.info", 
  "||2008xianzhang.info", 
  ".213.so", 
  "21andy.com/blog", 
  "24smile.org", 
  ".2shared.com", 
  ".315lz.com", 
  "||32red.com", 
  "||36rain.com", 
  ".3boys2girls.com", 
  "||4bluestones.biz", 
  "||4chan.org", 
  "||4shared.com", 
  "5i01.com", 
  "taiwannation.50webs.com", 
  "||51.ca", 
  ".5maodang.com", 
  "64memo", 
  "64tianwang.com", 
  "64wiki.com", 
  "666kb.com", 
  "6park.com", 
  "||6park.com", 
  "||www.6v6dota.com", 
  "||7capture.com", 
  ".881903.com/page/zh-tw/", 
  ".888.com", 
  "||881903.com", 
  "89-64.org", 
  "||89-64.org", 
  ".9001700.com", 
  "|http://908taiwan.org/", 
  "|http://91porn.com", 
  ".92ccav.com", 
  "||9bis.com", 
  "||9bis.net", 
  "||a-normal-day.com", 
  "a5.com.ru", 
  "|http://aamacau.com", 
  "|http://cdn*.abc.com/", 
  ".ablwang.com", 
  ".aboluowang.com", 
  "||aboluowang.com", 
  ".aboutgfw.com", 
  "||acgkj.com", 
  "actimes.com.au", 
  "||aculo.us", 
  "||addictedtocoffee.de", 
  "adultfriendfinder.com", 
  "adultkeep.net/peepshow/members/main.htm", 
  "||advanscene.com", 
  "||advertfan.com", 
  "||aenhancers.com", 
  "||af.mil", 
  "aiph.net", 
  "||aiph.net", 
  ".aisex.com", 
  "||ait.org.tw", 
  "|http://aiweiwei.com", 
  ".aiweiweiblog.com", 
  "||aiweiweiblog.com", 
  "||www.ajsands.com", 
  "|https://fbcdn*.akamaihd.net/", 
  "||akiba-online.com", 
  "||al-qimmah.net", 
  "||alabout.com", 
  "||alasbarricadas.org", 
  "alexlur.org", 
  "aliengu.com", 
  "||alkasir.com", 
  "allgirlsallowed.org", 
  "alliance.org.hk", 
  ".allinfa.com", 
  "|http://allinfa.com", 
  "||allmovie.com", 
  "||alternate-tools.com", 
  "alvinalexander.com", 
  "alwaysdata.com", 
  "||alwaysdata.com", 
  "||alwaysdata.net", 
  "||am730.com.hk", 
  "amazon.com/Prisoner-State-Secret-Journal-Premier", 
  "ameblo.jp", 
  "||ameblo.jp", 
  "||americangreencard.com", 
  "||amiblockedornot.com", 
  ".amnesty.org", 
  "||amnesty.org", 
  ".amnestyusa.org", 
  "||amnestyusa.org", 
  ".amoiist.com", 
  "analyze-v.com", 
  "||anchorfree.com", 
  "||ancsconf.org", 
  "||andfaraway.net", 
  "||android.com", 
  "||angularjs.org", 
  "animecrazy.net", 
  "||anobii.com", 
  ".anonymizer.com", 
  "anontext.com", 
  ".answering-islam.org", 
  "|http://www.antd.org", 
  "||anthonycalzadilla.com", 
  ".antiwave.net", 
  "|http://antiwave.net", 
  "||aobo.com.au", 
  "||aolchannels.aol.com", 
  "video.aol.ca/video-detail", 
  "video.aol.co.uk/video-detail", 
  "video.aol.com", 
  "||video.aol.com", 
  "www.aolnews.com", 
  "||aomiwang.com", 
  "video.ap.org", 
  ".apetube.com", 
  "||apiary.io", 
  ".apigee.com", 
  "||apigee.com", 
  "appledaily.com", 
  "archive.is", 
  "||archive.org", 
  ".arctosia.com", 
  "|http://arctosia.com", 
  "||areca-backup.org", 
  "||army.mil", 
  "artsy.net", 
  ".asahichinese.com", 
  "||asahichinese.com", 
  "asdfg.jp/dabr", 
  "|http://japanfirst.asianfreeforum.com/", 
  ".asiaharvest.org", 
  "||asiaharvest.org", 
  "asianews.it", 
  "||asianwomensfilm.de", 
  "||askstudent.com", 
  ".askynz.net", 
  "||askynz.net", 
  "||assembla.com", 
  "||astonmartinnews.com", 
  "||astrill.com", 
  "||atc.org.au", 
  ".atchinese.com", 
  "|http://atchinese.com", 
  "atgfw.org", 
  "||atj.org.tw", 
  ".atlaspost.com", 
  "||atlaspost.com", 
  ".atnext.com", 
  "||atnext.com", 
  "avaaz.org", 
  "||avaaz.org", 
  "||avast.com", 
  ".avdb.in", 
  "||avdb.in", 
  ".avdb.tv", 
  "||avdb.tv", 
  "||avidemux.org", 
  "||avoision.com", 
  "||axureformac.com", 
  "forum.baby-kingdom.com", 
  "babynet.com.hk", 
  "backchina.com", 
  "||backchina.com", 
  ".backpackers.com.tw/forum", 
  "backtotiananmen.com", 
  "badoo.com", 
  "|http://*2.bahamut.com.tw", 
  "||baidu.jp", 
  "||baixing.me", 
  "hen.bao.li", 
  "bannedbook.org", 
  "||bannedbook.org", 
  ".barenakedislam.com", 
  "||barnabu.co.uk", 
  "bayvoice.net", 
  "||bayvoice.net", 
  "dajusha.baywords.com", 
  ".bbc.co.uk*chinese", 
  ".bbc.co.uk/tv", 
  ".bbc.co.uk*zhongwen", 
  "news.bbc.co.uk/onthisday*newsid_2496000/2496277", 
  "newsforums.bbc.co.uk", 
  ".bbcchinese.com", 
  "||bbcchinese.com", 
  "|http://bbc.in", 
  ".bbg.gov", 
  "||bbsfeed.com", 
  "bbsland.com", 
  ".bcc.com.tw/board", 
  ".bcchinese.net", 
  ".bebo.com", 
  "||bebo.com", 
  "||beijing1989.com", 
  "beijingspring.com", 
  "||beijingspring.com", 
  ".berlintwitterwall.com", 
  "||berlintwitterwall.com", 
  ".bestforchina.org", 
  "||bestforchina.org", 
  ".bestvpnservice.com", 
  "||bet365.com", 
  ".betfair.com", 
  ".bettween.com", 
  "||bettween.com", 
  "||betvictor.com", 
  ".bewww.net", 
  ".beyondfirewall.com", 
  "||bfnn.org", 
  "||bfsh.hk/", 
  "biantailajiao.com", 
  "biantailajiao.in", 
  ".bic2011.org", 
  "bigfools.com", 
  ".bignews.org", 
  "||bignews.org", 
  ".bigsound.org/portnoy", 
  "||bill2-software.com", 
  "billypan.com/wiki/%E9%A6%96%E9%A0%81", 
  "||billywr.com", 
  "bipic.net", 
  ".bit.ly", 
  "|http://bit.ly", 
  "||bitcointalk.org", 
  ".bitshare.com", 
  "||bitshare.com", 
  "bjzc.org", 
  "||bjzc.org/", 
  "tor.blingblingsquad.net", 
  ".blinkx.com", 
  "||blinkx.com", 
  "blinw.com", 
  ".blip.tv", 
  "||blip.tv/", 
  ".blockcn.com", 
  "||blockcn.com", 
  "||blog.de", 
  "||blogblog.com", 
  ".blogcatalog.com", 
  "||blogcatalog.com", 
  ".blogger.com", 
  "||blogger.com", 
  "blogimg.jp", 
  "||blog.kangye.org", 
  ".bloglines.com", 
  "||bloglines.com", 
  "||bloglovin.com", 
  "rconversation.blogs.com", 
  "/^https?:\\/\\/[^\\/]+blogspot\\.(.*)/", 
  "blogtd.net", 
  ".blogtd.org", 
  "|http://blogtd.org", 
  "||bloodshed.net", 
  ".bloomberg.cn", 
  "||bloomberg.cn", 
  ".bloomberg.com", 
  "||bloomberg.com", 
  "bloomberg.de", 
  "||bloomberg.de", 
  "||bloomfortune.com", 
  "||bnrmetal.com", 
  "boardreader.com/thread", 
  "||boardreader.com", 
  "bonbonme.com", 
  "||boobstagram.com", 
  "||book.com.tw", 
  "||books.com.tw", 
  "||botanwang.com", 
  ".bot.nu", 
  ".bowenpress.com", 
  "||bowenpress.com", 
  "dl.box.net", 
  "||dl.box.net", 
  "boxun.com", 
  "||boxun.com", 
  ".boxun.tv", 
  "||boxun.tv", 
  "boxunblog.com", 
  "||boxunblog.com", 
  ".boxunclub.com", 
  "||br.st", 
  "||brandonhutchinson.com", 
  "||braumeister.org", 
  ".break.com", 
  "||break.com", 
  ".breakingtweets.com", 
  "||breakingtweets.com", 
  "||breakwall.net", 
  ".briefdream.com/%E7%B4%A0%E6%A3%BA", 
  "brightkite.com", 
  "||brightkite.com", 
  "brizzly.com", 
  "||brizzly.com", 
  "broadbook.com", 
  "ibros.org", 
  "brucewang.net", 
  "||bt95.com", 
  "|http://btdigg.org", 
  ".budaedu.org", 
  "||budaedu.org", 
  ".bullog.org", 
  "||bullog.org", 
  ".bullogger.com", 
  "||bullogger.com", 
  "|http://www.businessinsider.com.au/*", 
  "|http://static*.businessinsider.com/", 
  ".businessweek.com", 
  ".businesstimes.com.cn", 
  "|http://businesstimes.com.cn", 
  "||bugclub.org", 
  "||buugaa.com", 
  ".buzzhand.com", 
  "buzzurl.jp", 
  "bwsj.hk", 
  "||bx.tl", 
  "holz.byethost8.com", 
  ".c-spanvideo.org", 
  "||c-spanvideo.org", 
  "||c-est-simple.com", 
  ".cacnw.com", 
  ".cactusvpn.com", 
  "||cactusvpn.com", 
  ".cafepress.com", 
  ".cahr.org.tw", 
  ".calameo.com/books", 
  "cn.calameo.com", 
  "|http://cn.calameo.com", 
  "||cams.com", 
  ".cams.org.sg", 
  "canadameet.com", 
  "|http://bbs.cantonese.asia/", 
  ".canyu.org", 
  ".cao.im", 
  ".caobian.info", 
  "||caobian.info", 
  "|http://catcatbox.com/forum.php*", 
  "caochangqing.com", 
  "||caochangqing.com", 
  "cari.com.my", 
  "||catch22.net", 
  "||catfightpayperview.xxx", 
  ".catholic.org.hk", 
  "||catholic.org.hk", 
  "catholic.org.tw", 
  "||catholic.org.tw", 
  "||cattt.com", 
  ".cbsnews.com/video", 
  "||ccavtop10.com", 
  ".ccdtr.org", 
  "||ccdtr.org", 
  ".ccim.org", 
  "cclife.org", 
  ".ccthere.com", 
  ".cctongbao.com/article/2078732", 
  "ccue.ca", 
  "ccue.com", 
  ".cgdepot.org", 
  "|http://cgdepot.org", 
  "||cdig.info", 
  "cdjp.org", 
  "||cdjp.org/", 
  ".cdnews.com.tw", 
  "cdp1998.org", 
  "||cdp1998.org", 
  "cdp2006.org", 
  "||cdp2006.org", 
  ".cdpa.url.tw", 
  "cdpusa.org", 
  "cdpweb.org", 
  "||cdpweb.org", 
  "cdpwu.org", 
  "||cdpwu.org", 
  "||cdw.com", 
  ".cecc.gov", 
  "||cecc.gov", 
  "||cellulo.info", 
  "||cenci.tk", 
  "||cenews.eu", 
  "||centralnation.com", 
  ".centurys.net", 
  "|http://centurys.net", 
  ".cfhks.org.hk", 
  ".cftfc.com", 
  "||chandoo.org", 
  ".change.org", 
  "|http://change.org", 
  ".changp.com", 
  "||changp.com", 
  ".chapm25.com", 
  ".chaturbate.com", 
  "chengmingmag.com", 
  ".chenguangcheng.com", 
  "||chenguangcheng.com", 
  "chenpokong.com", 
  "||cherrysave.com", 
  ".chhongbi.org", 
  "|http://chicagoncmtv.com", 
  ".china-week.com", 
  "china101.com", 
  "||china101.com", 
  "||china21.com", 
  "china21.org", 
  "||china21.org", 
  ".china5000.us", 
  "chinaaffairs.org", 
  "||chinaaffairs.org", 
  "||chinaaid.me", 
  "chinaaid.us", 
  "chinaaid.org", 
  "chinaaid.net", 
  "chinacomments.org", 
  "||chinacomments.org", 
  "chinachange.org", 
  "chinachannel.hk", 
  "||chinachannel.hk", 
  ".chinadigitaltimes.net", 
  "||chinadigitaltimes.net", 
  ".chinaeweekly.com", 
  "||chinaeweekly.com", 
  "||chinafreepress.org", 
  ".chinagate.com", 
  "chinageeks.org", 
  "chinagfw.org", 
  "||chinagfw.org", 
  ".chinagreenparty.org", 
  "||chinagreenparty.org", 
  ".chinahush.com", 
  "chinalawtranslate.com", 
  "chinaxchina.com/howto", 
  ".chinainperspective.com", 
  "chinainperspective.net/ArtShow.aspx?", 
  "||chinainperspective.net", 
  ".chinainperspective.org", 
  "||chinainperspective.org", 
  "||chinainterimgov.org", 
  "chinalawandpolicy.com", 
  ".chinamule.com", 
  "||chinamule.com", 
  "chinamz.org", 
  ".chinarightsia.org", 
  "chinasocialdemocraticparty.com", 
  "||chinasocialdemocraticparty.com", 
  "chinasoul.org", 
  "||chinasoul.org", 
  "chinatimes.com", 
  "chinatweeps.com", 
  "chinaway.org", 
  ".chinaworker.info", 
  "||chinaworker.info", 
  "chinayouth.org.hk", 
  "chinayuanmin.org", 
  "||chinayuanmin.org", 
  ".chinese-hermit.net", 
  "chinese-memorial.org", 
  "||chinesedailynews.com", 
  ".chinesen.de", 
  "||chinesen.de", 
  "chinesenewsnet.com", 
  ".chinesepen.org", 
  ".chinesetalks.net/ch", 
  ".chingcheong.com", 
  "||chingcheong.com", 
  "chn.chosun.com", 
  "christianstudy.com", 
  "||christianstudy.com", 
  "christusrex.org/www1/sdc", 
  "||chrlcg-hk.org", 
  "||chrome.com", 
  "||chromeadblock.com", 
  "||chromium.org", 
  "chubun.com", 
  "chuizi.net", 
  "||chuizi.net", 
  "||christiantimes.org.hk", 
  ".chrlawyers.hk", 
  "||allaboutalpha.com", 
  ".circlethebayfortibet.org", 
  ".citizenlab.org", 
  "citizensradio.org", 
  "city9x.com", 
  ".civicparty.hk", 
  "||civicparty.hk", 
  "civilhrfront.org", 
  "||civilhrfront.org", 
  ".civilmedia.tw", 
  "psiphon.civisec.org", 
  "||cjb.net", 
  ".ck101.com", 
  "||ck101.com", 
  "||classicalguitarblog.net", 
  ".clb.org.hk", 
  ".clipfish.de", 
  "|http://www.cmoinc.org", 
  "||cms.gov", 
  "||cna.com.tw", 
  ".cnavista.com.tw/shop/stores_app", 
  ".cnd.org", 
  "||cnd.org/", 
  "wiki.cnitter.com", 
  ".cnn.com/video", 
  "news.cnyes.com", 
  "||cochina.co", 
  "||cochina.org", 
  ".code1984.com/64", 
  "||codeshare.io", 
  "|http://tosh.comedycentral.com", 
  "comefromchina.com", 
  "||comefromchina.com", 
  "||compileheart.com", 
  "||conoyo.com", 
  ".contactmagazine.net", 
  ".convio.net", 
  "|http://www.cool18.com/bbs*/", 
  ".coolaler.com", 
  "||coolaler.com", 
  "coolder.com", 
  "||coolder.com", 
  "||coolloud.org.tw", 
  "corumcollege.com", 
  "||couchdbwiki.com", 
  "||cotweet.com", 
  "cpj.org", 
  "||cpj.org/", 
  "crackle.com", 
  "||crackle.com", 
  "crd-net.org", 
  "creaders.net", 
  "||creaders.net", 
  ".crossthewall.net", 
  "||crossthewall.net", 
  "csdparty.com", 
  "||csdparty.com", 
  "||csuchen.de", 
  ".ctfriend.net", 
  "cts.com.tw", 
  "|http://library.usc.cuhk.edu.hk/Default.aspx?url=dflms%2fsub%2f%2f1%2fdict%2f50", 
  "|http://mjlsh.usc.cuhk.edu.hk", 
  ".cuhkacs.org/~benng", 
  ".cuihua.org", 
  "||cuihua.org", 
  ".cuiweiping.net", 
  "||cuiweiping.net", 
  "||curvefish.com", 
  ".culture.tw", 
  "||culture.tw", 
  ".cw.com.tw", 
  "|http://forum.cyberctm.com", 
  "||cyberghostvpn.com", 
  "||cynscribe.com", 
  "cytode.us", 
  "||ifan.cz.cc", 
  "||mike.cz.cc", 
  "||nic.cz.cc", 
  "cl.d0z.net", 
  ".dabr.co.uk", 
  "||dabr.co.uk", 
  "dabr.mobi", 
  "||dabr.mobi", 
  "||dabr.me", 
  "dadazim.com", 
  "||dadazim.com", 
  ".dadi360.com", 
  "dafagood.com", 
  "dafahao.com", 
  "||dalailama.ru", 
  ".dailidaili.com", 
  "||dailidaili.com", 
  ".dailymotion.com", 
  ".dajiyuan.com", 
  ".dajiyuan.eu", 
  "dalailama.com", 
  ".dalailamaworld.com", 
  "||dalailamaworld.com", 
  "dalianmeng.org", 
  "||dalianmeng.org", 
  ".danke4china.net", 
  "||danke4china.net", 
  ".danwei.org", 
  "daolan.net", 
  "daxa.cn", 
  "||daxa.cn/", 
  "cn.dayabook.com", 
  ".daylife.com/topic/dalai_lama", 
  ".ddc.com.tw", 
  "||de-sci.org", 
  ".de-sci.org", 
  "lists.debian.org", 
  "packages.debian.org/zh-cn/lenny/gpass", 
  "||delcamp.net", 
  "delicious.com/GFWbookmark", 
  ".democrats.org", 
  "||democrats.org", 
  "||desc.se/", 
  ".destroy-china.jp", 
  "||deutsche-welle.de", 
  "||dev102.com", 
  "||deviantart.com", 
  "||deviantart.net", 
  "||devio.us", 
  "||devpn.com", 
  "|http://www.dfanning.com", 
  "||dfas.mil", 
  ".diaoyuislands.org", 
  "||diaoyuislands.org", 
  "static.digg.com", 
  "|http://digiland.tw/", 
  "||digitalnomadsproject.org", 
  ".diigo.com", 
  "||diigo.com", 
  "||furl.net", 
  ".dipity.com", 
  "||directcreative.com", 
  "|http://www.discogs.com/", 
  ".discuss.com.hk", 
  "||discuss.com.hk", 
  "disp.cc", 
  ".dit-inc.us", 
  "||dit-inc.us", 
  ".dizhidizhi.com", 
  "djangosnippets.org", 
  "||dl-laby.jp", 
  "||dlsite.com", 
  "||dmcdn.net", 
  "||dnscrypt.org", 
  "||dns2go.com", 
  "||dnssec.net", 
  ".dojin.com", 
  ".dok-forum.net", 
  "||dolc.de", 
  "||dollf.com", 
  ".domain.club.tw", 
  "dongde.com", 
  "dongtaiwang.com", 
  "||dongtaiwang.com", 
  ".dongtaiwang.net", 
  "||dongtaiwang.net", 
  ".dongyangjing.com", 
  ".dontfilter.us", 
  "||dontmovetochina.com", 
  ".dotplane.com", 
  "||dotplane.com", 
  "||dotsub.com", 
  "doubleaf.com", 
  "||dougscripts.com", 
  "dowei.org", 
  "||doxygen.org", 
  "dphk.org", 
  "dpp.org.tw", 
  "||dpp.org.tw", 
  "||weigegebyc.dreamhosters.com", 
  "||drgan.net", 
  "||dropbox.com", 
  "||dropboxusercontent.com", 
  "drsunacademy.com", 
  ".drtuber.com", 
  ".dscn.info", 
  "||dtiblog.com", 
  "||dtic.mil", 
  "dtiserv2.com", 
  "||duckduckgo.com", 
  ".duckload.com/download", 
  "||duckmylife.com", 
  ".duihua.org", 
  "||duihua.org", 
  "||duihuahrjournal.org", 
  ".duoweitimes.com", 
  "||duoweitimes.com", 
  "duping.net", 
  "||duplicati.com", 
  "dupola.com", 
  "dupola.net", 
  "||dvorak.org", 
  ".dw.de", 
  "|http://dw.de", 
  ".dw-world.com", 
  "||dw-world.com", 
  ".dw-world.de", 
  "http://dw-world.de", 
  "www.dwheeler.com", 
  "dwnews.com", 
  "||dwnews.com", 
  "dwnews.net", 
  "||dwnews.net", 
  "xys.dxiong.com", 
  "dy24k.info", 
  "||dynawebinc.com", 
  ".dyndns.org", 
  ".dzze.com", 
  "||e-gold.com", 
  ".e-gold.com", 
  "|http://g.e-hentai.org/", 
  "e-info.org.tw", 
  ".e-traderland.net/board", 
  ".e123.hk", 
  ".eastturkestan.com", 
  ".eastturkistan-gov.org", 
  ".eastturkistangovernmentinexile.us", 
  "hkjp.easyweb.hk", 
  "ebookbrowse.com", 
  "ebookee.com", 
  "ecministry.net", 
  "bbs.ecstart.com", 
  "||edgecastcdn.net", 
  "twimg\\.edgesuite\\.net\\/\\/?appledaily", 
  "edicypages.com", 
  "edoors.com", 
  ".edubridge.com", 
  "||edubridge.com", 
  "||eevpn.com", 
  "efcc.org.hk", 
  "||efmoe.com", 
  "||eic-av.com", 
  "electionsmeter.com", 
  "||elgoog.im", 
  "||elpais.com", 
  ".eltondisney.com", 
  "||emacsblog.org", 
  ".emory.edu", 
  ".emule-ed2k.com", 
  "|http://emule-ed2k.com", 
  ".emuparadise.me", 
  "||enewstree.com", 
  "chinese.engadget.com", 
  "||englishfromengland.co.uk", 
  "||entermap.com", 
  "epochtimes-bg.com", 
  "||epochtimes-bg.com", 
  "epochtimes-romania.com", 
  "||epochtimes-romania.com", 
  "epochtimes.co.il", 
  "||epochtimes.co.il", 
  "epochtimes.co.kr", 
  "||epochtimes.co.kr", 
  "epochtimes.com", 
  "||epochtimes.com", 
  "epochtimes.de", 
  "epochtimes.fr", 
  ".epochtimes.ie", 
  "epochtimes.jp", 
  "epochtimes.ru", 
  "epochtimes.se", 
  "epochtimestr.com", 
  "||epochweekly.com", 
  "erabaru.net", 
  ".erepublik.com", 
  "||ernestmandel.org", 
  "||erights.net", 
  ".etaa.org.au", 
  "etaiwannews.com", 
  "||etizer.org", 
  ".ettoday.net", 
  "www.eulam.com", 
  "eventful.com", 
  "||exblog.jp", 
  "||blog.exblog.co.jp", 
  "@@||www.exblog.jp", 
  "|http://blog.excite.co.jp/", 
  "||expatshield.com", 
  "||exploader.net", 
  ".extremetube.com", 
  "eyevio.jp", 
  "||eyevio.jp", 
  ".eyny.com", 
  ".ezpc.tk/category/soft", 
  ".ezpeer.com", 
  ".facebook.com", 
  "||facebook.com", 
  "/^https?:\\/\\/[^\\/]+facebook\\.com/", 
  "@@||*v6.facebook.com", 
  "||connect.facebook.net", 
  "||facebookquotes4u.com", 
  "||facesofnyfw.com", 
  "||faiththedog.info", 
  ".fakku.net", 
  "falunart.org", 
  "||falunasia.info", 
  "falundafa.org", 
  "falundafamuseum.org", 
  "||falunhr.org", 
  "||fanglizhi.info", 
  "||fangong.org", 
  "fangongheike.com", 
  "fanqianghou.com", 
  "fapdu.com", 
  ".fawanghuihui.org", 
  "||fbcdn.net", 
  "fanqiangyakexi.net", 
  "fail.hk", 
  "||famunion.com", 
  ".fan-qiang.com", 
  ".fangbinxing.com", 
  "||fangbinxing.com", 
  "fangeming.com", 
  "||fanswong.com", 
  ".fanyue.info", 
  ".farwestchina.com", 
  "en.favotter.net", 
  "||faststone.org", 
  "favstar.fm", 
  "||favstar.fm", 
  "faydao.com/weblog", 
  "||fb.com", 
  "fb.me", 
  "||fb.me", 
  "||fbsbx.com", 
  "fc2.com", 
  ".fc2china.com", 
  "fc2blog.net", 
  "video.fdbox.com", 
  ".fdc89.jp", 
  "||fourface.nodesnoop.com", 
  "||feedburner.com", 
  "||feedzshare.com", 
  "||feelssh.com", 
  "feer.com", 
  "||feministteacher.com", 
  ".fengzhenghu.com", 
  "||fengzhenghu.com", 
  "fflick.com", 
  "fgmtv.net", 
  ".fgmtv.org", 
  ".files2me.com", 
  "|http://files2me.com", 
  ".fileserve.com/file", 
  "fillthesquare.org", 
  "||finalion.jp", 
  "findbook.tw", 
  ".fingerdaily.com", 
  "finler.net", 
  ".fireofliberty.org", 
  "||fireofliberty.org", 
  ".falsefire.com", 
  "||falsefire.com", 
  "fleshbot.com", 
  "||flickr.com", 
  "||staticflickr.com", 
  "flickrhivemind.net", 
  "yuming.flnet.org", 
  "|http://cn.fmnnow.com", 
  "blog.foolsmountain.com", 
  "www.forum4hk.com", 
  "pioneer-worker.forums-free.com", 
  "|http://4sq.com", 
  "||fotop.net", 
  "video.foxbusiness.com", 
  "||fringenetwork.com", 
  "||flecheinthepeche.fr", 
  "||focustaiwan.tw", 
  ".focusvpn.com", 
  "||fofg.org", 
  ".fooooo.com", 
  "||fooooo.com", 
  "footwiball.com", 
  "||fourthinternational.org", 
  "||foxdie.us", 
  "||foxsub.com", 
  "foxtang.com", 
  "||fqrouter.com", 
  "||franklc.com", 
  ".freakshare.com", 
  "|http://freakshare.com", 
  "||free4u.com.ar", 
  "free-gate.org", 
  ".free.fr/adsl", 
  "||allonlinux.free.fr", 
  "||dimitrik.free.fr", 
  "kineox.free.fr", 
  "||puttycm.free.fr", 
  "||freealim.com", 
  "whitebear.freebearblog.org", 
  ".freechal.com", 
  ".freedomhouse.org", 
  "||freedomhouse.org", 
  ".freegao.com", 
  "||freegao.com", 
  ".free-hada-now.org", 
  ".freelotto.com", 
  "||freelotto.com", 
  "freeman2.com", 
  ".freeopenvpn.com", 
  "freemoren.com", 
  "freemorenews.com", 
  "freenet-china.org", 
  "freenewscn.com", 
  ".freeoz.org/bbs", 
  "||freeoz.org", 
  "||www.bulbous.freeserve.co.uk", 
  "||freessh.us", 
  "free4u.com.ar", 
  ".free-ssh.com", 
  "||free-ssh.com", 
  ".freeforums.org", 
  "||freenetproject.org", 
  ".freeoz.org", 
  ".freetibet.net", 
  "||freetibet.org", 
  "|http://freetibetanheroes.org", 
  "||freewallpaper4.me", 
  ".freewebs.com", 
  "||freeweibo.com", 
  ".freexinwen.com", 
  ".freeyoutubeproxy.net", 
  "||freeyoutubeproxy.net", 
  "friendfeed.com", 
  "friendfeed-media.com/e99a4ebe2fb4c1985c2a58775eb4422961aa5a2e", 
  "|http://ff.im", 
  "|http://www.zensur.freerk.com/", 
  "freevpn.nl", 
  ".fring.com", 
  "||fring.com", 
  "||frommel.net", 
  ".frontlinedefenders.org", 
  "||fscked.org", 
  ".fsurf.com", 
  ".ftchinese.com/story/001054103", 
  ".ftchinese.com/*video", 
  ".ftchinese.com/comments", 
  ".fuckcnnic.net", 
  "||fuckcnnic.net", 
  "fuckgfw.org", 
  "fulue.com", 
  ".funf.tw", 
  "funp.com", 
  "||furinkan.com", 
  ".futurechinaforum.org", 
  "||futuremessage.org", 
  ".fuyin.net", 
  "||fw.cm", 
  "fzh999.com", 
  "fzh999.net", 
  "||gabocorp.com", 
  ".gaeproxy.com", 
  "||galenwu.com", 
  "||game735.com", 
  "gamebase.com.tw", 
  "||gamer.com.tw", 
  ".gamer.com.tw", 
  ".gamez.com.tw", 
  "||gamez.com.tw", 
  ".gaoming.net", 
  "||gaoming.net", 
  "ganges.com", 
  ".gaopi.net", 
  "|http://gaopi.net", 
  ".gaozhisheng.org", 
  ".gaozhisheng.net", 
  "gardennetworks.com", 
  "||gardennetworks.org", 
  "72.52.81.22", 
  "||gartlive.com", 
  "||gather.com", 
  "||gaymap.cc", 
  ".gazotube.com", 
  "||gazotube.com", 
  "||gcc.org.hk", 
  "||gclooney.com", 
  ".gcpnews.com", 
  ".gdbt.net/forum", 
  "gdzf.org", 
  "||geek-art.net", 
  "geekerhome.com/2010/03/xixiang-project-cross-gfw", 
  "||geekmanuals.com", 
  "||genuitec.com", 
  ".geocities.co.jp", 
  ".geocities.com/SiliconValley/Circuit/5683/download.html", 
  "hk.geocities.com", 
  "geocities.jp", 
  "||geohot.com", 
  "||geometrictools.com", 
  "||get-digital-help.com", 
  ".getchu.com", 
  "||getfoxyproxy.org", 
  ".getfreedur.com", 
  "||getgom.com", 
  ".getlantern.org", 
  "||getlantern.org", 
  ".getjetso.com/forum", 
  "getiton.com", 
  ".getsocialscope.com", 
  "gfw.org.ua", 
  ".ggssl.com", 
  "||ggssl.com", 
  "||ghost.org", 
  "||ghut.org", 
  "||giga-web.jp", 
  "|http://tw.gigacircle.com", 
  "|http://cn.giganews.com/", 
  "gigporno.ru", 
  "||gimpshop.com", 
  "||girlbanker.com", 
  "|http://softwaredownload.gitbooks.io/", 
  "|https://gist.github.com", 
  "|http://cthlo.github.io/hktv/", 
  "||glennhilton.com", 
  "globaljihad.net", 
  "globalmuseumoncommunism.org", 
  "||globalrescue.net", 
  ".globalvoicesonline.org", 
  "||globalvoicesonline.org", 
  "gmbd.cn", 
  "||gmhz.org", 
  "||gnci.org.hk", 
  "||goagent.biz", 
  "||goagentplus.com", 
  "godfootsteps.org", 
  "||godfootsteps.org", 
  ".gokbayrak.com", 
  "||goldbetsports.com", 
  "|http://www.goldenmelody.com.tw", 
  "||goldwave.com", 
  "gongmeng.info", 
  "gongm.in", 
  "gongminliliang.com", 
  ".gongwt.com", 
  ".goodreads.com", 
  "||goodreads.com", 
  ".goodreaders.com", 
  "||goodreaders.com", 
  "||goofind.com", 
  ".googlesile.com", 
  ".gopetition.com", 
  "||gopetition.com", 
  "||gotw.ca/", 
  "grandtrial.org", 
  "||graphis.ne.jp", 
  "||gravatar.com", 
  "greatfirewall.biz", 
  "||greatfirewallofchina.net", 
  ".greatfirewallofchina.org", 
  "||greatfirewallofchina.org", 
  ".greenparty.org.tw", 
  "||greenpeace.org", 
  "great-firewall.com", 
  "great-roc.org", 
  "greatroc.org", 
  "greatzhonghua.org", 
  ".greenpeace.com.tw", 
  ".greenvpn.net", 
  "||greenvpn.net", 
  "gs-discuss.com", 
  "||gtricks.com", 
  "guancha.org", 
  ".gun-world.net", 
  "||gutteruncensored.com", 
  "||gvm.com.tw", 
  ".gzm.tv", 
  "||gzone-anime.info", 
  "||agoogleaday.com", 
  "||chromeexperiments.com", 
  "||chromercise.com", 
  "||data-vocabulary.org", 
  "||g.co", 
  "||ggpht.com", 
  "||gmail.com", 
  "||gmodules.com", 
  "||goo.gl", 
  "/^https?:\\/\\/[^\\/]+google\\.(.*)/", 
  "||googleapis.com", 
  "||googleartproject.com", 
  "||googlecode.com", 
  "||googlecommerce.com", 
  "||googledomains.com", 
  "||googleearth.com", 
  "||googledrive.com", 
  "||googlegroups.com", 
  "||googlehosted.com", 
  "||googlelabs.com", 
  "||googlemail.com", 
  "||googleplus.com", 
  "||googlesource.com", 
  "||googleusercontent.com", 
  "||googlevideo.com", 
  "||groups.google.cn", 
  "||gvt0.com", 
  "||gvt1.com", 
  "||html5rocks.com", 
  "||panoramio.com", 
  "||recaptcha.net", 
  "|http://sipml5.org/", 
  ".appspot.com", 
  "||appspot.com", 
  "/^https?:\\/\\/[^\\/]+appspot\\.com/", 
  "chinaaid.net", 
  "echofon.com", 
  "||golang.org", 
  "||greasespot.net", 
  "||www.klip.me", 
  "@@||site.locql.com", 
  "@@||download.syniumsoftware.com", 
  "|http://ub0.cc", 
  "wozy.in", 
  "||google.com", 
  "||google.co.jp", 
  "||google.co.hk", 
  "||bbc.co.uk", 
  "||googleapis.com", 
  "||googlesyndication.com", 
  "||github.com", 
  "||wikipedia.org"
];

/*
* This file is part of Adblock Plus <http://adblockplus.org/>,
* Copyright (C) 2006-2014 Eyeo GmbH
*
* Adblock Plus is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License version 3 as
* published by the Free Software Foundation.
*
* Adblock Plus is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Adblock Plus.  If not, see <http://www.gnu.org/licenses/>.
*/

function createDict()
{
    var result = {};
    result.__proto__ = null;
    return result;
}

function getOwnPropertyDescriptor(obj, key)
{
    if (obj.hasOwnProperty(key))
    {
        return obj[key];
    }
    return null;
}

function extend(subclass, superclass, definition)
{
    if (Object.__proto__)
    {
        definition.__proto__ = superclass.prototype;
        subclass.prototype = definition;
    }
    else
    {
        var tmpclass = function(){}, ret;
        tmpclass.prototype = superclass.prototype;
        subclass.prototype = new tmpclass();
        subclass.prototype.constructor = superclass;
        for (var i in definition)
        {
            if (definition.hasOwnProperty(i))
            {
                subclass.prototype[i] = definition[i];
            }
        }
    }
}

function Filter(text)
{
    this.text = text;
    this.subscriptions = [];
}
Filter.prototype = {
    text: null,
    subscriptions: null,
    toString: function()
    {
        return this.text;
    }
};
Filter.knownFilters = createDict();
Filter.elemhideRegExp = /^([^\/\*\|\@"!]*?)#(\@)?(?:([\w\-]+|\*)((?:\([\w\-]+(?:[$^*]?=[^\(\)"]*)?\))*)|#([^{}]+))$/;
Filter.regexpRegExp = /^(@@)?\/.*\/(?:\$~?[\w\-]+(?:=[^,\s]+)?(?:,~?[\w\-]+(?:=[^,\s]+)?)*)?$/;
Filter.optionsRegExp = /\$(~?[\w\-]+(?:=[^,\s]+)?(?:,~?[\w\-]+(?:=[^,\s]+)?)*)$/;
Filter.fromText = function(text)
{
    if (text in Filter.knownFilters)
    {
        return Filter.knownFilters[text];
    }
    var ret;
    if (text.charAt(0) == "!")
    {
        ret = new CommentFilter(text);
    }
    else
    {
        ret = RegExpFilter.fromText(text);
    }
    Filter.knownFilters[ret.text] = ret;
    return ret;
};

function InvalidFilter(text, reason)
{
    Filter.call(this, text);
    this.reason = reason;
}
extend(InvalidFilter, Filter, {
    reason: null
});

function CommentFilter(text)
{
    Filter.call(this, text);
}
extend(CommentFilter, Filter, {
});

function ActiveFilter(text, domains)
{
    Filter.call(this, text);
    this.domainSource = domains;
}
extend(ActiveFilter, Filter, {
    domainSource: null,
    domainSeparator: null,
    ignoreTrailingDot: true,
    domainSourceIsUpperCase: false,
    getDomains: function()
    {
        var prop = getOwnPropertyDescriptor(this, "domains");
        if (prop)
        {
            return prop;
        }
        var domains = null;
        if (this.domainSource)
        {
            var source = this.domainSource;
            if (!this.domainSourceIsUpperCase)
            {
                source = source.toUpperCase();
            }
            var list = source.split(this.domainSeparator);
            if (list.length == 1 && list[0].charAt(0) != "~")
            {
                domains = createDict();
                domains[""] = false;
                if (this.ignoreTrailingDot)
                {
                    list[0] = list[0].replace(/\.+$/, "");
                }
                domains[list[0]] = true;
            }
            else
            {
                var hasIncludes = false;
                for (var i = 0; i < list.length; i++)
                {
                    var domain = list[i];
                    if (this.ignoreTrailingDot)
                    {
                        domain = domain.replace(/\.+$/, "");
                    }
                    if (domain == "")
                    {
                        continue;
                    }
                    var include;
                    if (domain.charAt(0) == "~")
                    {
                        include = false;
                        domain = domain.substr(1);
                    }
                    else
                    {
                        include = true;
                        hasIncludes = true;
                    }
                    if (!domains)
                    {
                        domains = createDict();
                    }
                    domains[domain] = include;
                }
                domains[""] = !hasIncludes;
            }
            this.domainSource = null;
        }
        return this.domains;
    },
    sitekeys: null,
    isActiveOnDomain: function(docDomain, sitekey)
    {
        if (this.getSitekeys() && (!sitekey || this.getSitekeys().indexOf(sitekey.toUpperCase()) < 0))
        {
            return false;
        }
        if (!this.getDomains())
        {
            return true;
        }
        if (!docDomain)
        {
            return this.getDomains()[""];
        }
        if (this.ignoreTrailingDot)
        {
            docDomain = docDomain.replace(/\.+$/, "");
        }
        docDomain = docDomain.toUpperCase();
        while (true)
        {
            if (docDomain in this.getDomains())
            {
                return this.domains[docDomain];
            }
            var nextDot = docDomain.indexOf(".");
            if (nextDot < 0)
            {
                break;
            }
            docDomain = docDomain.substr(nextDot + 1);
        }
        return this.domains[""];
    },
    isActiveOnlyOnDomain: function(docDomain)
    {
        if (!docDomain || !this.getDomains() || this.getDomains()[""])
        {
            return false;
        }
        if (this.ignoreTrailingDot)
        {
            docDomain = docDomain.replace(/\.+$/, "");
        }
        docDomain = docDomain.toUpperCase();
        for (var domain in this.getDomains())
        {
            if (this.domains[domain] && domain != docDomain && (domain.length <= docDomain.length || domain.indexOf("." + docDomain) != domain.length - docDomain.length - 1))
            {
                return false;
            }
        }
        return true;
    }
});

function RegExpFilter(text, regexpSource, contentType, matchCase, domains, thirdParty, sitekeys)
{
    ActiveFilter.call(this, text, domains, sitekeys);
    if (contentType != null)
    {
        this.contentType = contentType;
    }
    if (matchCase)
    {
        this.matchCase = matchCase;
    }
    if (thirdParty != null)
    {
        this.thirdParty = thirdParty;
    }
    if (sitekeys != null)
    {
        this.sitekeySource = sitekeys;
    }
    if (regexpSource.length >= 2 && regexpSource.charAt(0) == "/" && regexpSource.charAt(regexpSource.length - 1) == "/")
    {
        var regexp = new RegExp(regexpSource.substr(1, regexpSource.length - 2), this.matchCase ? "" : "i");
        this.regexp = regexp;
    }
    else
    {
        this.regexpSource = regexpSource;
    }
}
extend(RegExpFilter, ActiveFilter, {
    domainSourceIsUpperCase: true,
    length: 1,
    domainSeparator: "|",
    regexpSource: null,
    getRegexp: function()
    {
        var prop = getOwnPropertyDescriptor(this, "regexp");
        if (prop)
        {
            return prop;
        }
        var source = this.regexpSource.replace(/\*+/g, "*").replace(/\^\|$/, "^").replace(/\W/g, "\\$&").replace(/\\\*/g, ".*").replace(/\\\^/g, "(?:[\\x00-\\x24\\x26-\\x2C\\x2F\\x3A-\\x40\\x5B-\\x5E\\x60\\x7B-\\x7F]|$)").replace(/^\\\|\\\|/, "^[\\w\\-]+:\\/+(?!\\/)(?:[^\\/]+\\.)?").replace(/^\\\|/, "^").replace(/\\\|$/, "$").replace(/^(\.\*)/, "").replace(/(\.\*)$/, "");
        var regexp = new RegExp(source, this.matchCase ? "" : "i");
        this.regexp = regexp;
        return regexp;
    },
    contentType: 2147483647,
    matchCase: false,
    thirdParty: null,
    sitekeySource: null,
    getSitekeys: function()
    {
        var prop = getOwnPropertyDescriptor(this, "sitekeys");
        if (prop)
        {
            return prop;
        }
        var sitekeys = null;
        if (this.sitekeySource)
        {
            sitekeys = this.sitekeySource.split("|");
            this.sitekeySource = null;
        }
        this.sitekeys = sitekeys;
        return this.sitekeys;
    },
    matches: function(location, contentType, docDomain, thirdParty, sitekey)
    {
        if (this.getRegexp().test(location) && this.isActiveOnDomain(docDomain, sitekey))
        {
            return true;
        }
        return false;
    }
});
RegExpFilter.prototype["0"] = "#this";
RegExpFilter.fromText = function(text)
{
    var blocking = true;
    var origText = text;
    if (text.indexOf("@@") == 0)
    {
        blocking = false;
        text = text.substr(2);
    }
    var contentType = null;
    var matchCase = null;
    var domains = null;
    var sitekeys = null;
    var thirdParty = null;
    var collapse = null;
    var options;
    var match = text.indexOf("$") >= 0 ? Filter.optionsRegExp.exec(text) : null;
    if (match)
    {
        options = match[1].toUpperCase().split(",");
        text = match.input.substr(0, match.index);
        for (var _loopIndex6 = 0; _loopIndex6 < options.length; ++_loopIndex6)
        {
            var option = options[_loopIndex6];
            var value = null;
            var separatorIndex = option.indexOf("=");
            if (separatorIndex >= 0)
            {
                value = option.substr(separatorIndex + 1);
                option = option.substr(0, separatorIndex);
            }
            option = option.replace(/-/, "_");
            if (option in RegExpFilter.typeMap)
            {
                if (contentType == null)
                {
                    contentType = 0;
                }
                contentType |= RegExpFilter.typeMap[option];
            }
            else if (option.charAt(0) == "~" && option.substr(1) in RegExpFilter.typeMap)
            {
                if (contentType == null)
                {
                    contentType = RegExpFilter.prototype.contentType;
                }
                contentType &= ~RegExpFilter.typeMap[option.substr(1)];
            }
            else if (option == "MATCH_CASE")
            {
                matchCase = true;
            }
            else if (option == "~MATCH_CASE")
            {
                matchCase = false;
            }
            else if (option == "DOMAIN" && typeof value != "undefined")
            {
                domains = value;
            }
            else if (option == "THIRD_PARTY")
            {
                thirdParty = true;
            }
            else if (option == "~THIRD_PARTY")
            {
                thirdParty = false;
            }
            else if (option == "COLLAPSE")
            {
                collapse = true;
            }
            else if (option == "~COLLAPSE")
            {
                collapse = false;
            }
            else if (option == "SITEKEY" && typeof value != "undefined")
            {
                sitekeys = value;
            }
            else
            {
                return new InvalidFilter(origText, "Unknown option " + option.toLowerCase());
            }
        }
    }
    if (!blocking && (contentType == null || contentType & RegExpFilter.typeMap.DOCUMENT) && (!options || options.indexOf("DOCUMENT") < 0) && !/^\|?[\w\-]+:/.test(text))
    {
        if (contentType == null)
        {
            contentType = RegExpFilter.prototype.contentType;
        }
        contentType &= ~RegExpFilter.typeMap.DOCUMENT;
    }
    try
    {
        if (blocking)
        {
            return new BlockingFilter(origText, text, contentType, matchCase, domains, thirdParty, sitekeys, collapse);
        }
        else
        {
            return new WhitelistFilter(origText, text, contentType, matchCase, domains, thirdParty, sitekeys);
        }
    }
    catch (e)
    {
        return new InvalidFilter(origText, e);
    }
};
RegExpFilter.typeMap = {
    OTHER: 1,
    SCRIPT: 2,
    IMAGE: 4,
    STYLESHEET: 8,
    OBJECT: 16,
    SUBDOCUMENT: 32,
    DOCUMENT: 64,
    XBL: 1,
    PING: 1,
    XMLHTTPREQUEST: 2048,
    OBJECT_SUBREQUEST: 4096,
    DTD: 1,
    MEDIA: 16384,
    FONT: 32768,
    BACKGROUND: 4,
    POPUP: 268435456,
    ELEMHIDE: 1073741824
};
RegExpFilter.prototype.contentType &= ~ (RegExpFilter.typeMap.ELEMHIDE | RegExpFilter.typeMap.POPUP);

function BlockingFilter(text, regexpSource, contentType, matchCase, domains, thirdParty, sitekeys, collapse)
{
    RegExpFilter.call(this, text, regexpSource, contentType, matchCase, domains, thirdParty, sitekeys);
    this.collapse = collapse;
}
extend(BlockingFilter, RegExpFilter, {
    collapse: null
});

function WhitelistFilter(text, regexpSource, contentType, matchCase, domains, thirdParty, sitekeys)
{
    RegExpFilter.call(this, text, regexpSource, contentType, matchCase, domains, thirdParty, sitekeys);
}
extend(WhitelistFilter, RegExpFilter, {
});

function Matcher()
{
    this.clear();
}
Matcher.prototype = {
    filterByKeyword: null,
    keywordByFilter: null,
    clear: function()
    {
        this.filterByKeyword = createDict();
        this.keywordByFilter = createDict();
    },
    add: function(filter)
    {
        if (filter.text in this.keywordByFilter)
        {
            return;
        }
        var keyword = this.findKeyword(filter);
        var oldEntry = this.filterByKeyword[keyword];
        if (typeof oldEntry == "undefined")
        {
            this.filterByKeyword[keyword] = filter;
        }
        else if (oldEntry.length == 1)
        {
            this.filterByKeyword[keyword] = [oldEntry, filter];
        }
        else
        {
            oldEntry.push(filter);
        }
        this.keywordByFilter[filter.text] = keyword;
    },
    remove: function(filter)
    {
        if (!(filter.text in this.keywordByFilter))
        {
            return;
        }
        var keyword = this.keywordByFilter[filter.text];
        var list = this.filterByKeyword[keyword];
        if (list.length <= 1)
        {
            delete this.filterByKeyword[keyword];
        }
        else
        {
            var index = list.indexOf(filter);
            if (index >= 0)
            {
                list.splice(index, 1);
                if (list.length == 1)
                {
                    this.filterByKeyword[keyword] = list[0];
                }
            }
        }
        delete this.keywordByFilter[filter.text];
    },
    findKeyword: function(filter)
    {
        var result = "";
        var text = filter.text;
        if (Filter.regexpRegExp.test(text))
        {
            return result;
        }
        var match = Filter.optionsRegExp.exec(text);
        if (match)
        {
            text = match.input.substr(0, match.index);
        }
        if (text.substr(0, 2) == "@@")
        {
            text = text.substr(2);
        }
        var candidates = text.toLowerCase().match(/[^a-z0-9%*][a-z0-9%]{3,}(?=[^a-z0-9%*])/g);
        if (!candidates)
        {
            return result;
        }
        var hash = this.filterByKeyword;
        var resultCount = 16777215;
        var resultLength = 0;
        for (var i = 0, l = candidates.length; i < l; i++)
        {
            var candidate = candidates[i].substr(1);
            var count = candidate in hash ? hash[candidate].length : 0;
            if (count < resultCount || count == resultCount && candidate.length > resultLength)
            {
                result = candidate;
                resultCount = count;
                resultLength = candidate.length;
            }
        }
        return result;
    },
    hasFilter: function(filter)
    {
        return filter.text in this.keywordByFilter;
    },
    getKeywordForFilter: function(filter)
    {
        if (filter.text in this.keywordByFilter)
        {
            return this.keywordByFilter[filter.text];
        }
        else
        {
            return null;
        }
    },
    _checkEntryMatch: function(keyword, location, contentType, docDomain, thirdParty, sitekey)
    {
        var list = this.filterByKeyword[keyword];
        for (var i = 0; i < list.length; i++)
        {
            var filter = list[i];
            if (filter == "#this")
            {
                filter = list;
            }
            if (filter.matches(location, contentType, docDomain, thirdParty, sitekey))
            {
                return filter;
            }
        }
        return null;
    },
    matchesAny: function(location, contentType, docDomain, thirdParty, sitekey)
    {
        var candidates = location.toLowerCase().match(/[a-z0-9%]{3,}/g);
        if (candidates === null)
        {
            candidates = [];
        }
        candidates.push("");
        for (var i = 0, l = candidates.length; i < l; i++)
        {
            var substr = candidates[i];
            if (substr in this.filterByKeyword)
            {
                var result = this._checkEntryMatch(substr, location, contentType, docDomain, thirdParty, sitekey);
                if (result)
                {
                    return result;
                }
            }
        }
        return null;
    }
};

function CombinedMatcher()
{
    this.blacklist = new Matcher();
    this.whitelist = new Matcher();
    this.resultCache = createDict();
}
CombinedMatcher.maxCacheEntries = 1000;
CombinedMatcher.prototype = {
    blacklist: null,
    whitelist: null,
    resultCache: null,
    cacheEntries: 0,
    clear: function()
    {
        this.blacklist.clear();
        this.whitelist.clear();
        this.resultCache = createDict();
        this.cacheEntries = 0;
    },
    add: function(filter)
    {
        if (filter instanceof WhitelistFilter)
        {
            this.whitelist.add(filter);
        }
        else
        {
            this.blacklist.add(filter);
        }
        if (this.cacheEntries > 0)
        {
            this.resultCache = createDict();
            this.cacheEntries = 0;
        }
    },
    remove: function(filter)
    {
        if (filter instanceof WhitelistFilter)
        {
            this.whitelist.remove(filter);
        }
        else
        {
            this.blacklist.remove(filter);
        }
        if (this.cacheEntries > 0)
        {
            this.resultCache = createDict();
            this.cacheEntries = 0;
        }
    },
    findKeyword: function(filter)
    {
        if (filter instanceof WhitelistFilter)
        {
            return this.whitelist.findKeyword(filter);
        }
        else
        {
            return this.blacklist.findKeyword(filter);
        }
    },
    hasFilter: function(filter)
    {
        if (filter instanceof WhitelistFilter)
        {
            return this.whitelist.hasFilter(filter);
        }
        else
        {
            return this.blacklist.hasFilter(filter);
        }
    },
    getKeywordForFilter: function(filter)
    {
        if (filter instanceof WhitelistFilter)
        {
            return this.whitelist.getKeywordForFilter(filter);
        }
        else
        {
            return this.blacklist.getKeywordForFilter(filter);
        }
    },
    isSlowFilter: function(filter)
    {
        var matcher = filter instanceof WhitelistFilter ? this.whitelist : this.blacklist;
        if (matcher.hasFilter(filter))
        {
            return !matcher.getKeywordForFilter(filter);
        }
        else
        {
            return !matcher.findKeyword(filter);
        }
    },
    matchesAnyInternal: function(location, contentType, docDomain, thirdParty, sitekey)
    {
        var candidates = location.toLowerCase().match(/[a-z0-9%]{3,}/g);
        if (candidates === null)
        {
            candidates = [];
        }
        candidates.push("");
        var blacklistHit = null;
        for (var i = 0, l = candidates.length; i < l; i++)
        {
            var substr = candidates[i];
            if (substr in this.whitelist.filterByKeyword)
            {
                var result = this.whitelist._checkEntryMatch(substr, location, contentType, docDomain, thirdParty, sitekey);
                if (result)
                {
                    return result;
                }
            }
            if (substr in this.blacklist.filterByKeyword && blacklistHit === null)
            {
                blacklistHit = this.blacklist._checkEntryMatch(substr, location, contentType, docDomain, thirdParty, sitekey);
            }
        }
        return blacklistHit;
    },
    matchesAny: function(location, docDomain)
    {
        var key = location + " " + docDomain + " ";
        if (key in this.resultCache)
        {
            return this.resultCache[key];
        }
        var result = this.matchesAnyInternal(location, 0, docDomain, null, null);
        if (this.cacheEntries >= CombinedMatcher.maxCacheEntries)
        {
            this.resultCache = createDict();
            this.cacheEntries = 0;
        }
        this.resultCache[key] = result;
        this.cacheEntries++;
        return result;
    }
};
var defaultMatcher = new CombinedMatcher();

var direct = 'DIRECT;';

for (var i = 0; i < rules.length; i++) {
    defaultMatcher.add(Filter.fromText(rules[i]));
}

function FindProxyForURL(url, host) {
    if (defaultMatcher.matchesAny(url, host) instanceof BlockingFilter) {
        return proxy;
    }
    return direct;
}
