name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: JinnLynn/genpac
          ref: v2.0.1
          path: genpac

#      - uses: actions/checkout@v4
#        with:
#          repository: gfwlist/gfwlist
#          path: gfwlist

      - uses: petronny/git-config-user@master
        with:
          path: .

      - run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x

          wget https://gist.githubusercontent.com/wydy/3b186c67185317233c19e92905dd2656/raw/gfw.list
          genpac --pac-proxy="__PROXY__" --gfwlist-disabled --user-rule-from="gfw.list" -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac

          git add gfwlist.pac
          git commit -m "[$(LANG=C date)] auto update" || exit 0

          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

          git push origin master
